language: node_js
cache: yarn
notifications:
  webhooks:
    urls:
      - $GITTER_ROOM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

node_js:
  - 12
  - 10
  - 8

script: yarn test && yarn travis:coveralls

jobs:
  include:
    - stage: deploy
      name: 'Deploy packages'
      node_js: 12
      if: branch = production
      script: yarn semantic-release && yarn docs:publish && yarn examples:publish

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

