language: node_js
notifications:
  email: false
node_js:
  - 'node'

after_success:
  - npm run coveralls:travis
  - sh ./sh/prepublish.sh && semantic-release pre && sh ./sh/publish.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
sudo: false