language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

before_install:
  - npm install -g typings typescript
  - tsc --version
  - typings install

after_install:
  - tsc

script:
  - "npm test"
  - "npm run-script test-travis"

after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"