language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  webhooks:
    urls:
      - $GITTER_ROOM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

node_js:
  - 12
  - 10
  - 8

after_success: yarn travis:coveralls

jobs:
  include:
    - stage: deploy
      name: 'Deploy packages'
      node_js: 12
      if: branch = production
      script: yarn build
      deploy:
        - provider: script
          skip_cleanup: true
          script: yarn semantic-release && gulp docs:publish && gulp examples:publish

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

