blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/TypedProject/tsed/discussions
    about: Open a discussion that can be followed by the whole community on Github!
  - name: ðŸ’¬ Community channel (Slack)
    url: https://api.tsed.io/rest/slack/typedproject/tsed
    about: Join our slack workspace to discuss directly wiht the team!  
  - name: ðŸ’¬  Community group (Gitter deprecated)
    url: https://gitter.im/Tsed-io/Community
    about: You want to ask a question or discuss with other community members  


